### ISSUE TITLE
Cooperation proposal

### ISSUE THREAD

**Issue by Chris-N-K** [nipy/napari-nibabel#3]
Hi, 

I wrote a nifti format oriented IO plugin for napari based on nibabel at the end of last year. It worked fine for me and was quite similar to your solution but lacked the scale and translate support. Recently I included writers for image and label layers. During this task I discovered your solution.

Might it be interesting to combine our solutions?

Best regards,
Christopher N.-K.

**Comment by grlee77** [comment]
Hi Christopher, that would be great. I am not actively working on this repo at the moment, but opened it mainly so some previous work did not get lost. I no longer work directly with NIFTI files on a daily basis, but I am still interested in having this capability in Napari. It is mainly just an issue of finding free time to work on it!

How do you want to proceed? Is this something you think you can open PRs here corresponding to individual new features?

I had listed some other things currently missing here in the top level README. If we at least get orientation info and anisotropic voxel sizes handled properly that would be a great start toward having something we could start asking others to really use.

**Comment by Chris-N-K** [comment]
Hi Gregory, I need the functionalities for my research as I use or plan to use napari for several tasks. 

At present I included the affine matrix for orientation information, as napari now offers affine transformation. I think anisotropic voxel sizes are not further supported as the scaling factors in napari, but I might be wrong there. I would like to implement an information feature similar to the one in FSLeyes to directly display the header information, but I'm not totally sure how to handle that at the moment.

I would be open to gradually push the development of the plugin but might not be suited for project supervision. I would be open to merge my and your project to generate a more wholesome plugin ready for publishing on PyPi.

Best regards,
Christopher

**Comment by effigies** [comment]
@ch-n If you're working on this actively, would you like to be added as a maintainer to the project? [Nipy](https://nipy.org/) is open to people who have the time and energy being given wide latitude to work as they see fit.

**Comment by Chris-N-K** [comment]
@effigies that's fine by me. I never realy worked in a team over GitHub so are there some resources somewere what things I have to mind when working on and pushing to this repo?

Best Regards
Christopher

**Comment by Chris-N-K** [comment]
@grlee77 , @effigies I'm back from holidays, hoped to see a reply. How can I become a part of this repository / nipy? I would really like to participate.

Best regards,
Christopher

**Comment by effigies** [comment]
Ah, apologies, I missed that. [Nipy developer docs](https://nipy.org/nipy/devel/index.html) has conventions that people generally follow. It's been a bit since nipy was updated, so you could also look at [dipy](https://dipy.org/documentation/1.4.0./devel/) which I think has probably reviewed them more recently.

Just to break it down to the conventions I follow:

* Open issues for discussion, even if you don't expect feedback.
* Each PR should be on its own feature branch, and do just one thing, rather than lumping unrelated changes together.
* Give people time for review, but don't wait forever.

I've created a napari team for nipy and invited you to it, which has maintainer access to this repository. If you need additional access, please let me know.

**Comment by Chris-N-K** [comment]
No problem. Thanks for the invite I hope I can help the project.
